echo "We are trying this practical from linux EC2"
echo "We are from batch-25 & learning git/github"
echo "We are learning branching"
echo "our class name is young-minds"
echo "Our aws is completed now"
echo "Now started DEVOPS"