echo "We are trying this practical from linux EC2"
echo "We are from batch-25 and learning git/github"
echo "We re learning branching"
echo "I am learning Devops"
echo "Adding new line"
echo "I am Devops-2"
echo "Adding line"
